/*
 * This file is generated by jOOQ.
 */
package com.otto.lab4.jooq;


import com.otto.lab4.jooq.tables.AppUsers;
import com.otto.lab4.jooq.tables.HitChecks;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S335109 extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>s335109</code>
     */
    public static final S335109 S335109 = new S335109();

    /**
     * The table <code>s335109.app_users</code>.
     */
    public final AppUsers APP_USERS = AppUsers.APP_USERS;

    /**
     * The table <code>s335109.hit_checks</code>.
     */
    public final HitChecks HIT_CHECKS = HitChecks.HIT_CHECKS;

    /**
     * No further instances allowed
     */
    private S335109() {
        super("s335109", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.APP_USERS_ID_SEQ,
            Sequences.HIT_CHECKS_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            AppUsers.APP_USERS,
            HitChecks.HIT_CHECKS);
    }
}
