/*
 * This file is generated by jOOQ.
 */
package com.otto.lab4.jooq.tables.records;


import com.otto.lab4.jooq.tables.RestrictedRefreshTokens;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RestrictedRefreshTokensRecord extends TableRecordImpl<RestrictedRefreshTokensRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.restricted_refresh_tokens.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.restricted_refresh_tokens.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.restricted_refresh_tokens.token</code>.
     */
    public void setToken(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.restricted_refresh_tokens.token</code>.
     */
    public String getToken() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return RestrictedRefreshTokens.RESTRICTED_REFRESH_TOKENS.ID;
    }

    @Override
    public Field<String> field2() {
        return RestrictedRefreshTokens.RESTRICTED_REFRESH_TOKENS.TOKEN;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getToken();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getToken();
    }

    @Override
    public RestrictedRefreshTokensRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public RestrictedRefreshTokensRecord value2(String value) {
        setToken(value);
        return this;
    }

    @Override
    public RestrictedRefreshTokensRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RestrictedRefreshTokensRecord
     */
    public RestrictedRefreshTokensRecord() {
        super(RestrictedRefreshTokens.RESTRICTED_REFRESH_TOKENS);
    }

    /**
     * Create a detached, initialised RestrictedRefreshTokensRecord
     */
    public RestrictedRefreshTokensRecord(Integer id, String token) {
        super(RestrictedRefreshTokens.RESTRICTED_REFRESH_TOKENS);

        setId(id);
        setToken(token);
    }
}
