/*
 * This file is generated by jOOQ.
 */
package com.otto.lab4.jooq;


import com.otto.lab4.jooq.tables.AppUsers;
import com.otto.lab4.jooq.tables.HitChecks;
import com.otto.lab4.jooq.tables.records.AppUsersRecord;
import com.otto.lab4.jooq.tables.records.HitChecksRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AppUsersRecord> APP_USERS_NAME_KEY = Internal.createUniqueKey(AppUsers.APP_USERS, DSL.name("app_users_name_key"), new TableField[] { AppUsers.APP_USERS.NAME }, true);
    public static final UniqueKey<AppUsersRecord> APP_USERS_PKEY = Internal.createUniqueKey(AppUsers.APP_USERS, DSL.name("app_users_pkey"), new TableField[] { AppUsers.APP_USERS.ID }, true);
    public static final UniqueKey<HitChecksRecord> HIT_CHECKS_PKEY = Internal.createUniqueKey(HitChecks.HIT_CHECKS, DSL.name("hit_checks_pkey"), new TableField[] { HitChecks.HIT_CHECKS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<HitChecksRecord, AppUsersRecord> HIT_CHECKS__FK_USER = Internal.createForeignKey(HitChecks.HIT_CHECKS, DSL.name("fk_user"), new TableField[] { HitChecks.HIT_CHECKS.USER_ID }, Keys.APP_USERS_PKEY, new TableField[] { AppUsers.APP_USERS.ID }, true);
}
