/*
 * This file is generated by jOOQ.
 */
package com.otto.lab4.jooq;


import com.otto.lab4.jooq.tables.AppUsers;
import com.otto.lab4.jooq.tables.AuditedMethods;
import com.otto.lab4.jooq.tables.HitChecks;
import com.otto.lab4.jooq.tables.RestrictedRefreshTokens;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.app_users</code>.
     */
    public final AppUsers APP_USERS = AppUsers.APP_USERS;

    /**
     * The table <code>public.audited_methods</code>.
     */
    public final AuditedMethods AUDITED_METHODS = AuditedMethods.AUDITED_METHODS;

    /**
     * The table <code>public.hit_checks</code>.
     */
    public final HitChecks HIT_CHECKS = HitChecks.HIT_CHECKS;

    /**
     * The table <code>public.restricted_refresh_tokens</code>.
     */
    public final RestrictedRefreshTokens RESTRICTED_REFRESH_TOKENS = RestrictedRefreshTokens.RESTRICTED_REFRESH_TOKENS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.APP_USERS_ID_SEQ,
            Sequences.AUDITED_METHODS_ID_SEQ,
            Sequences.HIT_CHECKS_ID_SEQ,
            Sequences.RESTRICTED_REFRESH_TOKENS_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            AppUsers.APP_USERS,
            AuditedMethods.AUDITED_METHODS,
            HitChecks.HIT_CHECKS,
            RestrictedRefreshTokens.RESTRICTED_REFRESH_TOKENS);
    }
}
