/*
 * This file is generated by jOOQ.
 */
package com.otto.lab4.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in s335109.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>s335109.app_users_id_seq</code>
     */
    public static final Sequence<Integer> APP_USERS_ID_SEQ = Internal.createSequence("app_users_id_seq", S335109.S335109, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>s335109.hit_checks_id_seq</code>
     */
    public static final Sequence<Integer> HIT_CHECKS_ID_SEQ = Internal.createSequence("hit_checks_id_seq", S335109.S335109, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
