/*
 * This file is generated by jOOQ.
 */
package com.otto.lab4.jooq;


import com.otto.lab4.jooq.tables.AppUsers;
import com.otto.lab4.jooq.tables.HitChecks;


/**
 * Convenience access to all tables in s335109.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>s335109.app_users</code>.
     */
    public static final AppUsers APP_USERS = AppUsers.APP_USERS;

    /**
     * The table <code>s335109.hit_checks</code>.
     */
    public static final HitChecks HIT_CHECKS = HitChecks.HIT_CHECKS;
}
